import { Customer, InventoryItem, Supplier } from "./AppContext";

export const SEED_INVENTORY: InventoryItem[] = [
  {
    id: "inv-001",
    name: "Premium Arabica Beans",
    sku: "CF-001 • 1kg bag",
    category: "Coffee",
    quantity_on_hand: 8,
    unit_price: 14500,
    low_stock_threshold: 10,
    is_low_stock: true,
  },
  {
    id: "inv-002",
    name: "Organic Honey",
    sku: "MT-052 • 500ml",
    category: "Food",
    quantity_on_hand: 142,
    unit_price: 4200,
    low_stock_threshold: 10,
    is_low_stock: false,
  },
  {
    id: "inv-003",
    name: "Gishwati Green Tea",
    sku: "TEA-09 • 250g",
    category: "Beverages",
    quantity_on_hand: 45,
    unit_price: 2800,
    low_stock_threshold: 10,
    is_low_stock: false,
  },
  {
    id: "inv-004",
    name: "Cold Press Oil",
    sku: "OIL-12 • 1L Bottle",
    category: "Cooking",
    quantity_on_hand: 2,
    unit_price: 18000,
    low_stock_threshold: 5,
    is_low_stock: true,
  },
  {
    id: "inv-005",
    name: "Artisan Bread",
    sku: "BRD-03 • Loaf",
    category: "Bakery",
    quantity_on_hand: 12,
    unit_price: 2500,
    low_stock_threshold: 5,
    is_low_stock: false,
  },
  {
    id: "inv-006",
    name: "Whole Milk",
    sku: "MLK-01 • 1L",
    category: "Dairy",
    quantity_on_hand: 30,
    unit_price: 1300,
    low_stock_threshold: 10,
    is_low_stock: false,
  },
];

export const SEED_CUSTOMERS: Customer[] = [
  {
    id: "c-001",
    name: "Jean Bosco N.",
    phone: "+250 788 000 000",
    tier: "Tier 1 Merchant",
    total_credit: 450000,
    current_debt: 24500,
    overdue: true,
    last_transaction: "2h ago",
  },
  {
    id: "c-002",
    name: "Marie Claire U.",
    phone: "+250 722 111 222",
    tier: "",
    total_credit: 0,
    current_debt: 0,
    overdue: false,
    last_transaction: "Yesterday",
  },
  {
    id: "c-003",
    name: "Emmanuel K.",
    phone: "+250 788 333 444",
    tier: "",
    total_credit: 0,
    current_debt: 112000,
    overdue: false,
    last_transaction: "3 days ago",
  },
  {
    id: "c-004",
    name: "Divine R.",
    phone: "+250 722 555 666",
    tier: "",
    total_credit: 0,
    current_debt: 5200,
    overdue: false,
    last_transaction: "Oct 12",
  },
];

export const SEED_SUPPLIERS: Supplier[] = [
  {
    id: "s-001",
    name: "Kigali Wholesale Ltd",
    type: "Distributor • Electronics",
    payment_owed: 450000,
    last_purchase: "Oct 12, 2023",
    is_top_vendor: false,
    is_overdue: false,
  },
  {
    id: "s-002",
    name: "Musa Trading Co.",
    type: "Wholesale • Textiles",
    payment_owed: 0,
    last_purchase: "Oct 20, 2023",
    is_top_vendor: false,
    is_overdue: false,
  },
  {
    id: "s-003",
    name: "Rwanda Global Logistics",
    type: "Service • Logistics",
    payment_owed: 790000,
    last_purchase: "Yesterday",
    is_top_vendor: true,
    is_overdue: false,
  },
  {
    id: "s-004",
    name: "Nyabugogo Seeds",
    type: "Supplier • Agriculture",
    payment_owed: 0,
    last_purchase: "Aug 04",
    is_top_vendor: false,
    is_overdue: false,
  },
];

export const SEED_WEEKLY_REVENUE = [
  28000, 35000, 42000, 31000, 48000, 52000, 45000,
];
export const SEED_WEEK_LABELS = [
  "Mon",
  "Tue",
  "Wed",
  "Thu",
  "Fri",
  "Sat",
  "Sun",
];
export const SEED_BASE_REVENUE = 458200;
export const SEED_BASE_EXPENSES = 120000;

export const TRANSLATIONS: Record<string, Record<string, string>> = {
  en: {
    welcome: "Good morning,",
    revenue: "Today's Revenue",
    profit: "Today's Profit",
    weekly_sales: "This Week's Sales",
    outstanding: "Outstanding Debts",
    low_stock: "Low Stock",
    record: "Record",
    inventory: "Inventory",
    passport: "Passport",
    dashboard: "Home",
    record_sale: "Record Sale",
    record_expense: "Record Expense",
    product: "Product",
    quantity: "Quantity",
    total: "Total",
    save_sale: "Save Sale",
    save_expense: "Save Expense",
    category: "Category",
    amount: "Amount (RWF)",
    health_score: "Business Health Score",
    ai_coach: "AI Financial Coach",
    passport_label: "Digital Business Passport",
    suppliers: "Suppliers",
    customers: "Customers",
    reports: "Reports",
    settings: "Settings",
  },
  kin: {
    welcome: "Mwaramutse,",
    revenue: "Ibyacurujwe Uyu Munsi",
    profit: "Inyungu Uyu Munsi",
    weekly_sales: "Ibicuruzwa bya Icyumweru",
    outstanding: "Imyenda",
    low_stock: "Ibicuruzwa bya Gito",
    record: "Andika",
    inventory: "Ububiko",
    passport: "Pasiporo",
    dashboard: "Imbonerahamwe",
    record_sale: "Andika Icuruzwa",
    record_expense: "Andika Ibisohotse",
    product: "Igicuruzwa",
    quantity: "Ingano",
    total: "Igiteranyo",
    save_sale: "Bika Icuruzwa",
    save_expense: "Bika Ibisohotse",
    category: "Icyiciro",
    amount: "Amafaranga (RWF)",
    health_score: "Ubuziranenge bw'Ubucuruzi",
    ai_coach: "Umujyanama wa AI",
    passport_label: "Pasiporo y'Ubucuruzi",
    suppliers: "Abatangira",
    customers: "Abakiriya",
    reports: "Raporo",
    settings: "Igenamiterere",
  },
};
